FROM frolvlad/alpine-glibc:alpine-3.9_glibc-2.29

# Install useful things
RUN apk add --no-cache\
            wget \
            bzip2 \
            bash \
            findutils \
            ca-certificates \
            git \
            openssh-client \
            openssh \
            gnutls